# Generated by Django 4.1 on 2024-02-26 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('frequency', models.IntegerField(default=1)),
                ('number_of_times', models.IntegerField(default=1)),
                ('period', models.CharField(max_length=255)),
                ('goal', models.IntegerField()),
                ('num_of_tasks', models.IntegerField()),
                ('notes', models.CharField(default='empty', max_length=255)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
