# Generated by Django 4.1 on 2024-02-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0004_task_period_col_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='num_of_tasks',
            field=models.FloatField(),
        ),
    ]
