# Generated by Django 4.1 on 2024-04-01 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0020_habitview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HabitView',
        ),
    ]
